### ISSUE TITLE
Strange scroll after new data loads

### ISSUE THREAD

**Issue by pgbrown** [infinite-scroll/infinite-scroll#632]
I was wondering is someone could help. This is not an issue with the plugin but with my code I expect.

I have inherited development of this site and one thing they asked is for an infinite scroll feature.

It all works fine (to an extent). But when the new data loads the page does this strange scroll, which can be annoying when you are trying to add products to the cart, as suddenly your mouse is hovering over the wrong product..

The dev page is here

http://doorstep.vegemitetoast.com/index.php?route=product/category&path=1

If you scroll down a bit you'll see what happens. I'm probably missing something really obvious.

Thanks in advance for any help.

**Comment by lukeshumard** [comment]
You should try setting the `animate` option to false. This isn't really an error with the code at all, so I'm going to close this issue.
